
[general]
	#Puts all the added items into a new Every Compat tab instead of their own mod tabs. Be warned that if disabled it could cause some issue with some mods that have custom tabs
	creative_tab = true
	#Allows the mod to try to remap and convert other blocks and items from other compat mods that have been uninstalled from one world. This was made so one can uninstall such mods seamlessly having their blocks converted into Evety Compat counterparts
	remap_other_mods = false
	#Clears out and remaps all blocks registered by this mod belonging to uninstalled wood types to air or oak wood
	remap_self = true
	#Makes dynamic assets that are generated depend on loaded resource packs. Turn off to make them just use vanilla assets
	assets_depend_on_loaded_packs = true

[leaves_type]

	[leaves_type.minecraft]
		oak = true
		spruce = true
		birch = true
		jungle = true
		acacia = true
		dark_oak = true
		azalea = true
		flowering_azalea = true

	[leaves_type.biomesoplenty]
		fir = true
		redwood = true
		mahogany = true
		jacaranda = true
		palm = true
		willow = true
		dead = true
		magic = true
		umbran = true
		hellbark = true
		origin = true
		flowering_oak = true
		rainbow_birch = true
		yellow_autumn = true
		orange_autumn = true
		maple = true
		white_cherry = true
		pink_cherry = true

	[leaves_type.ecologics]
		coconut = true
		walnut = true

	[leaves_type.dynamictrees]
		spruce = true
		oak_undergrowth = true
		oak = true
		jungle_undergrowth = true
		jungle = true
		flowering_azalea = true
		dark_oak = true
		birch = true
		azalea = true
		acacia = true

	[leaves_type.dtbop]
		yellow_autumn = true
		willow = true
		white_cherry = true
		umbran = true
		spruce_undergrowth = true
		spruce_twiglet = true
		spruce_poplar = true
		sparse_oak = true
		sparse_acacia = true
		redwood = true
		rainbow_birch = true
		poplar = true
		pink_cherry = true
		palm = true
		orange_autumn = true
		oak_twiglet = true
		mega_dark_oak = true
		maple_twiglet = true
		maple = true
		mahogany = true
		magic_poplar = true
		jungle_twiglet = true
		jacaranda = true
		hellbark_bush = true
		hellbark = true
		flowering_oak_undergrowth = true
		flowering_oak = true
		fir = true
		dying = true
		dark_poplar = true
		dark_oak_twiglet = true
		cypress_willow = true
		acacia_undergrowth = true
		acacia_twiglet = true

	[leaves_type.dtphc2]
		tropical_pine = true
		rubber = true
		paperbark = true
		papaya = true
		maple = true
		eucalyptus = true
		date = true
		coconut = true
		cinnamon = true
		banana = true

	[leaves_type.tconstruct]
		earth_slime = true
		sky_slime = true
		ender_slime = true

	[leaves_type.dtecologics]
		walnut = true
		coconut = true

	[leaves_type.quark]
		blue_blossom = true
		lavender_blossom = true
		orange_blossom = true
		pink_blossom = true
		yellow_blossom = true
		red_blossom = true

	[leaves_type.dtquark]
		warm_blossom = true
		sweet_blossom = true
		sunny_blossom = true
		serene_blossom = true
		frosty_blossom = true
		fiery_blossom = true

[wood_type]

	[wood_type.minecraft]
		oak = true
		spruce = true
		birch = true
		jungle = true
		acacia = true
		dark_oak = true
		crimson = true
		warped = true

	[wood_type.ecologics]
		flowering_azalea = true
		coconut = true
		walnut = true
		azalea = true

	[wood_type.biomesoplenty]
		fir = true
		redwood = true
		cherry = true
		mahogany = true
		jacaranda = true
		palm = true
		willow = true
		dead = true
		magic = true
		umbran = true
		hellbark = true

	[wood_type.tconstruct]
		greenheart = true
		skyroot = true
		bloodshroom = true

	[wood_type.quark]
		azalea = true
		blossom = true

